# Generated by Django 5.0.6 on 2026-08-05 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Order created'), ('paid', 'Paid / active'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
